apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: spring-sample-app
spec:
  builder:
    name: default
    kind: ClusterBuilder
  serviceAccount: kpack-service-account
  cacheSize: "1.5Gi"
  source:
    blob:
      url: https://github.com/springone-tour-2020-cicd/spring-sample-app/releases/download/v1.0.0/spring-sample-app-1.0.0.jar
  tag: ciberkleid/spring-sample-app:latest